apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-python-app
spec:
  replicas: 3  # Number of desired pods
  selector:
    matchLabels:
      app: chatgpt-python-app
  template:
    metadata:
      labels:
        app: chatgpt-python-app
    spec:
      containers:
        - name: chatgpt-python-app
          image: kubecentral.azurecr.io/chatgpt_python_app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-python-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: chatgpt-python-app
